# Generated by Django 5.2.2 on 2025-08-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_migrate_simkl_periodoc_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='custom_url',
            field=models.URLField(default=''),
        ),
    ]
