# Generated by Django 5.2.2 on 2025-08-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_item_custom_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='custom_url',
        ),
        migrations.AddField(
            model_name='historicaltv',
            name='custom_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='tv',
            name='custom_url',
            field=models.URLField(default=''),
        ),
    ]
