# Generated by Django 5.2.2 on 2025-10-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_remove_item_custom_url_historicaltv_custom_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltv',
            name='custom_url',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='custom_url',
        ),
    ]
